FROM quay.io/podman/stable

ENV OCPVERSION="4.7.7"

ENV OCPRHCOSVERSION="4.7.0"

ENV HELPERNODEVERSION="v2beta1"

RUN dnf -y install keepalived iproute vim wget jq && \
    wget https://github.com/RedHatOfficial/ocp4-helpernode/releases/download/${HELPERNODEVERSION}/helpernodectl -O /usr/local/bin/helpernodectl && \
    chmod +x /usr/local/bin/helpernodectl && \
    mkdir -p /opt/helpernode/etc && \
    wget https://github.com/mikefarah/yq/releases/download/v4.10.0/yq_linux_amd64 -O /usr/local/bin/yq && \
    chmod +x /usr/local/bin/yq
    dnf -y clean all

COPY scripts/startup.sh /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/startup.sh"]
